foreach(name IN ITEMS PP-OCRv6_small_det PP-OCRv6_small_rec SLANet_plus)
    file(MAKE_DIRECTORY "${MODEL_DIRECTORY}/${name}")
    foreach(file IN ITEMS inference.onnx inference.yml)
        if(EXISTS "${MODEL_SOURCE}/${name}/${file}")
            file(COPY_FILE "${MODEL_SOURCE}/${name}/${file}"
                "${MODEL_DIRECTORY}/${name}/${file}" ONLY_IF_DIFFERENT)
        else()
            file(REMOVE "${MODEL_DIRECTORY}/${name}/${file}")
        endif()
    endforeach()
endforeach()
file(REMOVE "${MODEL_DIRECTORY}/model.onnx")
